### ISSUE TITLE
How to tell if its working?

### ISSUE THREAD

**Issue by vexxed12** [zentred/roblox-honda-limited-sniper-fixed#3]
ive set it all up correctly but im not sure if it is working

**Comment by vexxed12** [comment]
its not refreshing i think thats the problem

**Comment by zentred** [comment]
it's not looped atm
i couldnt be bothered

i just use my rolimons trade creator and wait like an hour then run this

i get like easy 100 trades with trade creating on rolimons

**Comment by zentred** [comment]
meaning you run it then when its done you close it

then next time do the same

**Comment by zentred** [comment]
also you will know if it s working because it will say the trade total / the trade its on like this

398/12 - trades completed

hopefully you know this does require you to actually have trades

**Comment by zentred** [comment]
commented about the wrong thing bruh


so idk about the limited sniper i dont use it anymore for a while
